name: Telegram Issue Open Notifications

on:
  issues:
    types:
      - opened

jobs:
  notify-issue:
    uses: jobmetric/github-notify/.github/workflows/telegram-issue-open-notify.yml@master
    with:
      date_format: jalali
      timezone: Asia/Tehran
    secrets:
      bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}

